import React from 'react';
import TodoList from './components/TodoList';
import './components/Todo.css';
import TodoForm from './components/TodoForm';

let data = [
  {
    task: 'Organize Garage',
    id: 1528817077286,
    completed: false
  },
  {
    task: 'Bake Cookies',
    id: 1528817084358,
    completed: false
  }
];


// design `App` to be the parent component of your application.
// this component is going to take care of state, and any change handlers you need to work with your state


class App extends React.Component {
  // you will need a place to store your state in this component.
  constructor(){
    super();
    this.state = {
      data
    }
  }

  toggleItem = (event, itemId) => {
    this.setState({
      data: this.state.data.map(item => {
        if(item.id === itemId){
          return {
            ...item,
            completed: !item.completed
          }
        }else{
          return item
        }
      })
    })
  }

  deleteCompleted = event => {
    event.preventDefault()

    this.setState({
      // filter out all groceries that are purchased
      data: this.state.data.filter(item => {
        // this is the same as:
        // item.purchased === false
        return !item.completed
      })
    })
  }



  addItem = (event, itemName) => {
    const newItem = {
      // usually the id is generated by backend,
      // but we can use a timestamp in this case
      id: Date.now(),
      task: itemName,
      completed: false
    }

    this.setState({
      // add the new item to the beginning of the list,
      // and merge in all the existing items
      data: [newItem, ...this.state.data]
    })
  }

    

  render() {
    return (
      <div>
        <div className="header">
          <h1>To-Do-List</h1>
          <TodoForm addItem={this.addItem} />
        </div>
        <TodoList toggleItem={this.toggleItem} data={this.state.data}/>
        <button className="clear-btn" onClick={this.deleteCompleted}>
            Delete Completed
        </button>
      </div>
    );
  }
}

export default App;